### ISSUE TITLE
Difference with Key Derivation

### ISSUE THREAD

**Issue by calve** [w8rbt/dpg#3]
Hi, I just discovered this project.

Not sure what you are trying to achieve; from what I understand, you generate password with the following algorithm;

`password = Hashfunction(passphrase+public_word)`.

In this situation, the generated password strength directly depends on the passphrase strength which, as you stated, needs to be memorized somewhere.

How is it different than https://en.wikipedia.org/wiki/Key_derivation_function, which is precisely what you do at  https://github.com/w8rbt/dpg/blob/master/python/dpg.py#L79 ?

**Comment by w8rbt** [comment]
I don't really understand your question. How is dpg different from a cryptographic KDF? 

dpg uses PBKDF2 (which is a KDF) to generate a deterministic key based on user input. This key is put into a byte queue. dpg pulls bytes from that queue and maps them to sets of words, letters and numbers to make useful, strong passwords for websites, etc. A KDF by itself is not really useful to a normal person in the context of using a password.

Set debug = True in dpg.py to see more verbose output. Also, try the C++ and Java implementations to see even more details.

Hope this explanation helps.

Brad
